#services:
#  db:
#    image: postgres:17
#    container_name: hh_db
#    restart: always
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#      POSTGRES_DB: hh_db
#    ports:
#      - "5432:5432"
#    volumes:
#      - pgdata:/var/lib/postgresql/data
#
#volumes:
#  pgdata:

services:
  postgres:
    image: postgres:18
    container_name: postgres_hh
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: pgadmin_hh
    restart: always
    env_file: .env
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data: